#!/bin/bash

BURP_PATH="/opt/burpsuite.jar"
BURP_URL="https://portswigger.net/burp/releases/startdownload?product=community&version=&type=Jar"

if [[ "$#" == 1 && ${1} == "-u" ]]
then
  if [ "$EUID" -ne 0 ]
  then
    sudo wget ${BURP_URL} -O ${BURP_PATH}
  else
    wget ${BURP_URL} -O ${BURP_PATH}
  fi

else
  java -jar ${BURP_PATH}
fi
